apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.svc.port }}
      targetPort: {{ .Values.svc.port }}
  type: {{ .Values.svc.type }}