apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

